### ISSUE TITLE
[Choose Your Fighter] UI Suggestions

### ISSUE THREAD

**Issue by librarianmage** [kernelmethod/QudMods#5]
I don't know how difficult it would be, but having the tile selector be a HorizScroll type with default, pick from pregen, and pick from blueprint as options might be a bit more visually compelling than the single menu option used right now.

It might also be neat to have the breadcrumb icon be the selected tile.

**Comment by kernelmethod** [comment]
Went ahead and made the breadcrumb icon the selected tile in CYF 0.6.0.

Probably going to put off the HorizScroll idea indefinitely since (a) the original purpose of the mod has expanded and now requires layers of submenus, and (b) some of the more popular expansion mods like [More Mutant Tiles](https://steamcommunity.com/sharedfiles/filedetails/?id=3174502319) have dozens and dozens of tiles, which can't be presented in that style of menu particularly well.

I'm still planning on changing the presentation at some point, though. I agree that the current presentation is not particularly nice (and the icons are too small).
